<?php

/**
 * Daftar kode bank Indonesia yang didukung untuk pencairan dana.
 */
return [
    'list' => [
        'BCA'       => 'Bank Central Asia',
        'BNI'       => 'Bank Negara Indonesia',
        'BRI'       => 'Bank Rakyat Indonesia',
        'MANDIRI'   => 'Bank Mandiri',
        'CIMB'      => 'CIMB Niaga',
        'BSI'       => 'Bank Syariah Indonesia',
        'PERMATA'   => 'Bank Permata',
        'DANAMON'   => 'Bank Danamon',
        'OCBC'      => 'Bank OCBC NISP',
        'MAYBANK'   => 'Bank Maybank Indonesia',
        'BTN'       => 'Bank Tabungan Negara',
        'BJB'       => 'Bank Jawa Barat & Banten',
        'MUAMALAT'  => 'Bank Muamalat',
        'MEGA'      => 'Bank Mega',
        'BTPN'       => 'Bank BTPN',
        'HSBC'      => 'Bank HSBC Indonesia',
        'CITIBANK'  => 'Citibank Indonesia',
        'UOB'       => 'Bank UOB Indonesia',
        'DBS'       => 'Bank DBS Indonesia',
        'STANDARD_CHARTERED' => 'Standard Chartered Bank',
        'BANK_OF_CHINA'      => 'Bank of China',
        'BANK_OF_AMERICA'    => 'Bank of America',
        'MUFG'      => 'MUFG Bank',
        'BCA_SYR'   => 'BCA Syariah',
        'BNI_SYR'   => 'BNI Syariah',
        'BRI_SYR'   => 'BRI Syariah',
        'MANDIRI_SYR' => 'Mandiri Syariah',
        'MAYBANK_SYR' => 'Maybank Syariah',
        'BTN_SYR'   => 'BTN Syariah',
        'BJB_SYR'   => 'BJB Syariah',
        'MEGA_SYR'  => 'Bank Mega Syariah',
        'SINARMAS'  => 'Bank Sinarmas',
        'COMMONWEALTH' => 'Commonwealth Bank',
        'ANZ'       => 'ANZ Indonesia',
        'ARTHA_GRAHA' => 'Bank Artha Graha',
        'BUMI_ARTA'  => 'Bank Bumi Arta',
        'CAPITAL'    => 'Bank Capital Indonesia',
        'CIMB_UUS'   => 'CIMB Niaga Syariah',
        'DANAMON_UUS' => 'Bank Danamon Syariah',
        'DINAR'      => 'Bank Dinar Indonesia',
        'GANESHA'    => 'Bank Ganesha',
        'INDEX_SELINDO' => 'Bank Index Selindo',
        'JTRUST'     => 'Bank JTrust Indonesia',
        'KROM'       => 'Bank Krom Indonesia',
        'MASPION'    => 'Bank Maspion',
        'MAYORA'     => 'Bank Mayora',
        'MITSUI'     => 'Mitsui Sumitomo Bank',
        'MIZUHO'     => 'Mizuho Bank',
        'MNC_INTERNASIONAL' => 'Bank MNC Internasional',
        'NEO_COMMERCE' => 'Bank Neo Commerce',
        'NOBU'       => 'Bank Nationalnobu',
        'OCBC_UUS'   => 'Bank OCBC NISP Syariah',
        'PANIN'      => 'Bank Panin',
        'RABOBANK'   => 'Rabobank International Indonesia',
        'RESONA'     => 'Resona Perdania Bank',
        'ROYAL'      => 'Bank Royal Indonesia',
        'SAHABAT_SAMPOERNA' => 'Bank Sahabat Sampoerna',
        'SEABANK'    => 'SeaBank Indonesia',
        'SHINHAN'    => 'Shinhan Bank Indonesia',
        'VICTORIA'   => 'Bank Victoria International',
        'WOORI'      => 'Woori Saudara Bank',
        'YUDHA_BHAKTI' => 'Bank Yudha Bhakti',
        'ALLO'       => 'Allo Bank',
        'ARTOS'      => 'Bank Jago',
        'JAGO'       => 'Bank Jago',
        'BLU'        => 'Blu by BCA Digital',
        'JENIUS'     => 'Jenius BTPN',
        'LINE_BANK'  => 'LINE Bank',
        'OK'         => 'OK Bank',
        'SUPER_BANK' => 'Superbank',
    ],

    // E-wallet / QRIS channels yang didukung
    'ewallets' => [
        'DANA'      => 'DANA',
        'GOPAY'     => 'GoPay',
        'OVO'       => 'OVO',
        'SHOPEEPAY' => 'ShopeePay',
        'LINKAJA'   => 'LinkAja',
    ],
];